# Generated by Django 3.2.24 on 2024-03-02 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20240301_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(help_text='Few sentences that showcase the appeal of the product', verbose_name='descriptive write-up'),
        ),
    ]
