# Generated by Django 3.2.24 on 2024-03-02 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(help_text='Size of the product, e.g., 200 gm, 500 gm, etc.', max_length=50, unique=True, verbose_name='size')),
                ('price', models.PositiveSmallIntegerField(help_text='Price payable by customer (Rs.)', verbose_name='selling price (Rs.)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skus', to='products.product')),
            ],
            options={
                'verbose_name': 'SKU',
                'verbose_name_plural': 'SKUs',
                'db_table': 'sku',
                'ordering': [],
            },
        ),
    ]
