# Generated by Django 3.2.24 on 2024-03-03 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_sku'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sku',
            old_name='price',
            new_name='selling_price',
        ),
        migrations.AddField(
            model_name='sku',
            name='cost_price',
            field=models.PositiveSmallIntegerField(help_text='Cost price of the product (Rs.)', null=True, verbose_name='cost price (Rs.)'),
        ),
        migrations.AddField(
            model_name='sku',
            name='platform_commission',
            field=models.PositiveSmallIntegerField(help_text='Commission charged by the platform (Rs.)', null=True, verbose_name='platform commission'),
        ),
    ]
