# Generated by Django 3.2.24 on 2024-03-03 18:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='measurement_unit',
            field=models.CharField(choices=[('gm', 'Gram'), ('kg', 'Kilogram'), ('mL', 'Milliliter'), ('L', 'Liter'), ('pc', 'Piece')], default='pc', help_text='Measurement unit of the product', max_length=2, verbose_name='measurement unit'),
        ),
        migrations.AddField(
            model_name='sku',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending for approval'), (2, 'Approved'), (3, 'Discontinued')], default=1, help_text='Status of the SKU', verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='size',
            field=models.CharField(help_text='Size of the product, e.g., 200 gm, 500 gm, etc.', max_length=150, validators=[django.core.validators.MaxValueValidator(999)], verbose_name='size'),
        ),
    ]
